# Generated by Django 4.2.20 on 2025-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я та призвіще")),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Оцінка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'review',
            },
        ),
    ]
