# Generated by Django 4.2.20 on 2025-06-02 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(1.0, message='Оцінка повинна бути не менше 1.00'), django.core.validators.MaxValueValidator(5.0, message='Оцінка повинна бути не більше 5.00')], verbose_name='Оцінка'),
        ),
    ]
