# Generated by Django 4.2.20 on 2025-08-08 16:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Політика конфіденційності', max_length=255, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержимое')),
                ('file', models.FileField(blank=True, null=True, upload_to='privacy_policies/', verbose_name='Файл (.docx или .txt)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'политику конфиденциальности',
                'verbose_name_plural': 'Политики конфиденциальности',
                'db_table': 'privacy_policy',
            },
        ),
    ]
