# Generated by Django 4.2.20 on 2025-08-10 11:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="ім'я")),
                ('sername', models.CharField(blank=True, max_length=100, null=True, verbose_name='прізвище')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса офісу')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='telegram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('messenger', models.CharField(blank=True, max_length=100, null=True, verbose_name='messenger')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='whatsapp')),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True, verbose_name='tiktok')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='роки досвіду')),
                ('winning_cases_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість виграних справ')),
                ('client_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='кількість клієнтів')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='about_me', verbose_name='фото на головній сторінці')),
                ('other_photos', models.ImageField(blank=True, null=True, upload_to='about_me', verbose_name='друга фотографія на сторінці "Про мене"')),
                ('main_about_me_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Короткий опис про мене на головній сторінці')),
                ('other_about_me_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Детальний опис про мене на сторінці "Про мене"')),
            ],
            options={
                'verbose_name': 'о себе',
                'verbose_name_plural': 'О себе',
                'db_table': 'about_me',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesWorkingWithMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='main.aboutme', verbose_name='Кому относится')),
            ],
            options={
                'verbose_name': 'Переваги роботи зі мною',
                'verbose_name_plural': 'Переваги роботи зі мною',
                'db_table': 'Advantages_working_with_me',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Політика конфіденційності'), ('public_offer', 'Публична оферта')], default='privacy_policy', max_length=20, verbose_name='Тип документа')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержимое')),
                ('file', models.FileField(blank=True, null=True, upload_to='privacy_policies/', verbose_name='Файл (.docx или .txt)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'legal_document',
            },
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
