# Generated by Django 4.2.20 on 2025-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutme_advantagesworkingwithme_legaldocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='other_photos',
            new_name='other_photo',
        ),
    ]
