# Generated by Django 4.2.20 on 2025-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_other_photos_aboutme_other_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='main_photo',
            new_name='first_photo',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='other_photo',
            new_name='second_photo',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='third_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about_me', verbose_name='третя фотографія в контактний блок на головній сторінці'),
        ),
    ]
