# Generated by Django 4.2.20 on 2025-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_main_photo_aboutme_first_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='viber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='viber'),
        ),
    ]
