# Generated by Django 4.2.20 on 2025-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutme_viber'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Потрібен дзвінок',
                'verbose_name_plural': 'Потрібні дзвінки',
                'db_table': 'need_call_back',
            },
        ),
    ]
