# Generated by Django 4.2.20 on 2025-08-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_needcallback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeedCallBack',
        ),
    ]
