# Generated by Django 4.2.20 on 2025-07-30 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'дату',
                'verbose_name_plural': 'Дати прийому',
                'db_table': 'appointment_date',
            },
        ),
        migrations.CreateModel(
            name='Reserved_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Час')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_times', to='appointments.appointmentdate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'зарезервовані години',
                'verbose_name_plural': 'Зарезервовані години',
                'db_table': 'reserved_time',
            },
        ),
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Час')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_times', to='appointments.appointmentdate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'час',
                'verbose_name_plural': 'Час прийому',
                'db_table': 'appointment_time',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=50, verbose_name='Призвіще')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +380XXXXXXXXX', regex='^\\+380\\d{9}$')])),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('reserved_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_time', to='appointments.reserved_time', verbose_name='Зарезервований час')),
            ],
            options={
                'verbose_name': 'клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'client',
            },
        ),
    ]
