# Generated by Django 4.2.20 on 2025-08-01 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'дату',
                'verbose_name_plural': 'Дати прийому',
                'db_table': 'appointment_date',
            },
        ),
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Час')),
                ('status', models.CharField(choices=[('RESERVED', 'Зарезервовано'), ('NOT_RESERVED', 'Не зарезервовано')], default='NOT_RESERVED', max_length=12, verbose_name='Статус резервації')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_times', to='appointments.appointmentdate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'час',
                'verbose_name_plural': 'Час прийому',
                'db_table': 'appointment_time',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=50, verbose_name='Призвіще')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +380XXXXXXXXX', regex='^\\+380\\d{9}$')])),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Замовлена послуга або консультіция')),
                ('reserved_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmenttime', verbose_name='Зарезервований час')),
            ],
            options={
                'verbose_name': 'клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'client',
            },
        ),
    ]
