# Generated by Django 4.2.20 on 2025-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_comment_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdate',
            name='status_date',
            field=models.CharField(choices=[('OVERDUE', 'Просрочено'), ('OPEN_ACCESS', 'Открыт'), ('CLOSED_ACCESS', 'Закрыт')], default='OPEN_ACCESS', max_length=13, verbose_name='Статус даты'),
        ),
    ]
