# Generated by Django 4.2.20 on 2025-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentdate_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdate',
            name='status_date',
            field=models.CharField(choices=[('OVERDUE', 'Прострочено'), ('OPEN_ACCESS', 'Відкритий'), ('CLOSED_ACCESS', 'Закритий')], default='OPEN_ACCESS', max_length=13, verbose_name='Статус дати'),
        ),
    ]
