# Generated by Django 4.2.20 on 2025-05-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images', verbose_name='Зображення')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'послугу',
                'verbose_name_plural': 'Послуги',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Заголовок блоку')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.service', verbose_name='До якої послуги відноситися')),
            ],
            options={
                'verbose_name': 'блок з інформацією',
                'verbose_name_plural': 'Блоки з інформацією',
                'db_table': 'serviceSection',
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Елемент списку')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicesection', verbose_name='До якої блоку відноситися')),
            ],
            options={
                'verbose_name': 'пункт в блок',
                'verbose_name_plural': 'Пункти в блоці',
                'db_table': 'sectionItem',
            },
        ),
    ]
