# Generated by Django 4.2.20 on 2025-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('service', 'Послуга'), ('consultation', 'Консультація')], default='service', max_length=20, verbose_name='Тип'),
        ),
    ]
