# Generated by Django 4.2.20 on 2025-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('service', 'Послуга'), ('consultation', 'Консультація')], default='service', max_length=20, verbose_name='Тип'),
        ),
    ]
